name: "Setup docker Env"
runs:
    using: "composite"
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to docker.io
          uses: docker/login-action@v2
          with:
              registry: docker.io
              username: docworld
              password: ${{ env.DOCKER_TOKEN }}
        - name: Login to Aliyuncs
          uses: docker/login-action@v2
          with:
              registry: registry.cn-beijing.aliyuncs.com
              username: ${{ env.ALIYUN_USERNAME }}
              password: ${{ env.ALIYUN_PASSWORD }}
        - name: Copy Tools
          shell: bash
          run: |
              cp -r tools ./${{ env.repo }}
              ./tools/install.sh
