name: Build Echarts Images

on:
    workflow_dispatch:
        inputs:
            is_test:
                description: "Test run"
                required: true
                type: boolean
                default: false

jobs:
    Build:
        runs-on: ubuntu-latest
        env:
            repo: echarts
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
            ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
            ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/login
            - name: Run Tools
              run: |
                  NODE_PATH=$(npm root --quiet -g) node ./tools/prepare.js repo-revision apache/echarts-website
                  NODE_PATH=$(npm root --quiet -g) node ./tools/prepare.js repo-release-tag apache/echarts
            - if: ${{ !inputs.is_test }}
              name: Build echarts doc
              uses: docker/build-push-action@v4.0.0
              with:
                  platforms: linux/amd64,linux/arm64
                  build-args: |
                      DOCWORLD_SOURCE=${{ env.DOCWORLD_SOURCE }}
                  context: ./echarts/
                  push: true
                  tags: |
                      docworld/echarts:latest
                      docworld/echarts:${{ env.tag_name }}
                      registry.cn-beijing.aliyuncs.com/docworld/echarts:latest
                      registry.cn-beijing.aliyuncs.com/docworld/echarts:${{ env.tag_name }}
            - if: ${{ inputs.is_test }}
              name: Test Build echarts doc
              uses: docker/build-push-action@v4.0.0
              with:
                  platforms: linux/amd64,linux/arm64
                  build-args: |
                      DOCWORLD_SOURCE=${{ env.DOCWORLD_SOURCE }}
                  context: ./echarts/
                  push: true
                  tags: |
                      registry.cn-beijing.aliyuncs.com/ikrong/docworld:echarts
    UpdateDockerDescription:
        if: ${{ !inputs.is_test }}
        needs: [Build]
        uses: ikrong/documents/.github/workflows/_updateDocker.yml@main
        with:
            repoName: echarts
        secrets: inherit
