name: Build ElementPlus Images

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: docworld
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get version
        uses: ikrong/actions-util@v1.0.0
        with:
          function: fetch
          params: '["https://api.github.com/repos/element-plus/element-plus/releases/latest","get",["tag_name"]]'
      - name: Build element-plus doc
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./element-plus/
          push: true
          tags: docworld/element-plus:latest, docworld/element-plus:${{ env.tag_name }}
  UpdateDockerDescription:
    needs: [Build]
    uses: ikrong/documents/.github/workflows/_updateDocker.yml@main
    with:
      repoName: element-plus
    secrets: inherit
