name: Build Sass Images

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to docker.io
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: docworld
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get version
        uses: ikrong/actions-util@v1.0.0
        with:
          function: fetch
          params: '["https://api.github.com/repos/sass/dart-sass/releases/latest","get",["tag_name"]]'
      - name: Build sass doc
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./sass/
          push: true
          tags: docworld/sass:latest, docworld/sass:${{ env.tag_name }}
  UpdateDockerDescription:
    needs: [Build]
    uses: ikrong/documents/.github/workflows/_updateDocker.yml@main
    with:
      repoName: sass
    secrets: inherit
