name: Build Tailwindcss Images

on:
    workflow_dispatch:
        inputs:
            is_test:
                description: "Test run"
                required: true
                type: boolean
                default: false

jobs:
    Build:
        if: ${{ !inputs.is_test }}
        runs-on: ubuntu-latest
        env:
            repo: tailwindcss
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
            ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
            ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/login
            - name: Run Tools
              run: |
                  NODE_PATH=$(npm root --quiet -g) node ./tools/prepare.js repo-revision tailwindlabs/tailwindcss.com
                  NODE_PATH=$(npm root --quiet -g) node ./tools/prepare.js repo-release-tag tailwindlabs/tailwindcss
            - name: Build Tailwindcss doc
              uses: docker/build-push-action@v4.0.0
              with:
                  platforms: linux/amd64,linux/arm64
                  context: ./tailwindcss/
                  push: true
                  build-args: |
                      DOCWORLD_SOURCE=${{ env.DOCWORLD_SOURCE }}
                  tags: |
                      docworld/tailwindcss:latest
                      docworld/tailwindcss:${{ env.tag_name }}
                      registry.cn-beijing.aliyuncs.com/docworld/tailwindcss:latest
                      registry.cn-beijing.aliyuncs.com/docworld/tailwindcss:${{ env.tag_name }}
    Test-Build:
        if: ${{ inputs.is_test }}
        runs-on: ubuntu-latest
        env:
            repo: tailwindcss
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
            ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
            ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/login
            - name: Run Tools
              run: |
                  NODE_PATH=$(npm root --quiet -g) node ./tools/prepare.js repo-revision tailwindlabs/tailwindcss.com
                  NODE_PATH=$(npm root --quiet -g) node ./tools/prepare.js repo-release-tag tailwindlabs/tailwindcss
            - name: Build Tailwindcss doc
              uses: docker/build-push-action@v4.0.0
              with:
                  platforms: linux/amd64,linux/arm64
                  context: ./tailwindcss/
                  push: true
                  build-args: |
                      DOCWORLD_SOURCE=${{ env.DOCWORLD_SOURCE }}
                  tags: |
                      registry.cn-beijing.aliyuncs.com/ikrong/docworld:tailwindcss
    UpdateDockerDescription:
        if: ${{ !inputs.is_test }}
        needs: [Build]
        uses: ikrong/documents/.github/workflows/_updateDocker.yml@main
        with:
            repoName: tailwindcss
        secrets: inherit
